config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  #if Rails.env.production?
    #match '/', to: 'spree/landings#index', via: 'get'
  #end
  mount Spree::Core::Engine, at: '/'
end
Spree::Core::Engine.add_routes do
  namespace :admin, path: Spree.admin_path do
    put 'products/:id/set_available', to: 'products#set_available', as: :make_product_available
    put 'products/:id/set_unavailable', to: 'products#set_unavailable', as: :set_unavailable_product
  end
end

Spree::Core::Engine.routes.append do
  namespace :admin, path: Spree.admin_path do
    resources :authors, path: 'artists' do
      resources :images, controller: :author_images do
        collection do
          post :update_positions
        end
      end
      resources :videos, path: 'library'
    end
  end

  resources :authors, only: [:index, :show], path: 'artists'
  resources :taxons do
    collection do
      get :products
    end
  end
  resources :videos, path: 'library' do
    collection do
      get :items
    end
  end
  get  'pages/contact_us'
  get  'pages/contact_artist'
  get  'pages/about_us', controller: 'pages', action: 'about_us'
  get  'pages/auctions', controller: 'pages', action: 'auctions'
  post 'pages/contact_us', controller: 'pages', action: 'contact_us_send'
  post 'pages/contact_artist', controller: 'pages', action: 'contact_artist_send'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable_entity', via: :all
end

app/models/concerns/spree/user_methods.rb
module Spree
  module UserMethods
    extend ActiveSupport::Concern

    include Spree::UserApiAuthentication
    include Spree::UserPaymentSource
    include Spree::UserReporting
    include Spree::RansackableAttributes

    included do
      has_many :role_users, class_name: 'Spree::RoleUser', foreign_key: :user_id, dependent: :destroy
      has_many :spree_roles, through: :role_users, class_name: 'Spree::Role', source: :role

      has_many :promotion_rule_users, class_name: 'Spree::PromotionRuleUser', foreign_key: :user_id, dependent: :destroy
      has_many :promotion_rules, through: :promotion_rule_users, class_name: 'Spree::PromotionRule'

      has_many :orders, foreign_key: :user_id, class_name: "Spree::Order"
      #has_many :store_credits, foreign_key: :user_id, class_name: 'Spree::StoreCredit'
      # remove store_credits from app

      belongs_to :ship_address, class_name: 'Spree::Address'
      belongs_to :bill_address, class_name: 'Spree::Address'

      self.whitelisted_ransackable_associations = %w[bill_address ship_address]
      self.whitelisted_ransackable_attributes = %w[id email]
    end

    # has_spree_role? simply needs to return true or false whether a user has a role or not.
    def has_spree_role?(role_in_question)
      spree_roles.any? { |role| role.name == role_in_question.to_s }
    end

    def last_incomplete_spree_order
      orders.incomplete.
        includes(line_items: [variant: [:images, :option_values, :product]]).
        order('created_at DESC').
        first
    end

    def analytics_id
      id
    end

    def total_available_store_credit
      #store_credits.reload.to_a.sum(&:amount_remaining)
    end
  end
end

app/models/spree/author.rb
# == Schema Information
#
# Table name: spree_authors
#
#  id                       :integer          not null, primary key
#  name                     :string
#  content                  :text
#  year_of_birth            :integer
#  year_of_death            :integer
#  category                 :integer
#  slug                     :string
#  foreign_link             :string
#  visible                  :boolean          default(TRUE)
#  meta_title               :string
#  meta_keywords            :string
#  meta_description         :string
#  layout                   :string
#  render_layout_as_partial :boolean          default(FALSE)
#  show_in_sidebar          :boolean          default(FALSE), not null
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#

class Spree::Author < ActiveRecord::Base

  CATEGORY_ARTIST   = 1
  CATEGORY_SCULPTOR = 2

  enum category: {
      artist:   CATEGORY_ARTIST,
      sculptor: CATEGORY_SCULPTOR
  }

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :category, presence: true
  validates :slug, :content, presence: true
  validates :slug, uniqueness: true
  validates :foreign_link, uniqueness: true, allow_blank: true

  has_many :products
  has_many :author_images, -> { order 'position ASC' }, as: :viewable
  delegate_belongs_to :author_images
  alias_method :images, :author_images

  has_many :videos, -> { order 'position ASC' }, :as => :watchable

  scope :visible, -> { where(visible: true) }
  scope :header_links, -> { where(show_in_header: true).visible }
  scope :sidebar_links, -> { where(show_in_sidebar: true).visible }

  before_validation :fill_slug

  def description
    content
  end

  def fill_slug
    self.slug = name.gsub(/\s+/, '_').underscore
  end

  protected
  def ransackable_attributes(auth_object = nil)
    super & %w(name)
  end
end

app/models/spree/author_image.rb
# == Schema Information
#
# Table name: spree_assets
#
#  id                      :integer          not null, primary key
#  viewable_id             :integer
#  viewable_type           :string
#  attachment_width        :integer
#  attachment_height       :integer
#  attachment_file_size    :integer
#  position                :integer
#  attachment_content_type :string
#  attachment_file_name    :string
#  type                    :string(75)
#  attachment_updated_at   :datetime
#  alt                     :text
#  created_at              :datetime
#  updated_at              :datetime
#

module Spree
  class AuthorImage < Asset
    belongs_to :viewable, :polymorphic => true, :touch => true

    validate :no_attachment_errors

    has_attached_file :attachment,
                      styles: { mini: '48x48>', small: '100x100>', author: '240x240>', large: '600x600>' },
                      default_style: :author,
                      url: '/spree/authors/:id/:style/:basename.:extension',
                      path: ':rails_root/public/spree/authors/:id/:style/:basename.:extension',
                      convert_options: { all: '-strip -auto-orient -colorspace sRGB' }
    validates_attachment :attachment,
      :presence => true,
      :content_type => { :content_type => %w(image/jpeg image/jpg image/png image/gif) }

    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    before_save :find_dimensions, if: :attachment_updated_at_changed?

    def author_id
      viewable_id if viewable_type == 'Spree::Author'
    end

    #used by admin products autocomplete
    def mini_url
      attachment.url(:mini, false)
    end

    def original_url
      attachment.url(:original, false)
    end

    def url_with_host_author
      "#{ActionController::Base.asset_host}#{original_url}"
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end
  end
end

app/models/spree/image_decorator.rb
Spree::Image.class_eval do

  def url_with_host
    "#{ActionController::Base.asset_host}#{mini_url}"
  end
end

app/models/spree/price_decorator.rb
Spree::Price.class_eval do

  attr_writer :price_before_discount
  def price_before_discount
    if discount
      amount + discount
    else
      amount
    end
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  belongs_to :author
  enum price_type: [ :real_price, :not_sale, :request_price ]
  delegate_belongs_to :master, :discount
  delegate_belongs_to :master, :price_before_discount
  self.whitelisted_ransackable_associations += %w(author)
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  scope :show_on_home, -> {where show_on_home: true}
  has_many :authors, through: :products
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  delegate_belongs_to :default_price, :discount
  delegate_belongs_to :default_price, :price_before_discount
end

app/models/spree/video_decorator.rb
Spree::Video.class_eval do
  attr_accessor :author_id
  belongs_to :author, -> {where spree_videos: {watchable_type: 'Spree::Author'}}, class_name: 'Author', foreign_key: :watchable_id
  scope :orderby, -> (opt) { order(opt.is_a?(Array) && opt[1] ? {opt[0] => opt[1]} : opt) }
  validates :youtube_ref, format: {with: /([\w-]+)(&.+)?$/, message: :incorrect_link, multiline: true}, if: Proc.new{|model| model.youtube_ref.present?}

  def embed_html(html5_config = {}, youtube_url_params = {})
#  if youtube_url_params.empty?
  #youtube_data.embed_html
  #else
    "<iframe width='560' height='315' src='//www.youtube.com/embed/#{youtube_ref}' frameborder='0' allowfullscreen></iframe>"
  #end
  end
end

app/controllers/spree/admin/author_images_controller.rb
module Spree
  module Admin
    class AuthorImagesController < ResourceController
      before_action :load_data

      create.before :set_viewable
      update.before :set_viewable

      def show
        redirect_to [:admin, @author, :images]
      end

      private

      def location_after_destroy
        admin_author_images_url(@author)
      end

      def location_after_save
        admin_author_images_url(@author)
      end

      def location_create_save
        admin_author_images_url(@author)
      end

      def location_update_save
        admin_author_images_url(@author)
      end

      def load_data
        @author = Author.find(params[:author_id])
      end

      def set_viewable
        @author_image.viewable_type = 'Spree::Author'
        @author_image.viewable_id = params[:author_image][:viewable_id]
      end

      def author_index_includes
        [
            author_images: [viewable: { option_values: :option_type }]
        ]
      end

      def author_edit_includes
        [
            author_images: { option_values: :option_type, images: :viewable }
        ]
      end
    end
  end
end

app/controllers/spree/admin/authors_controller.rb
module Spree
  module Admin
    class AuthorsController < ResourceController

      def index

      end
    end
  end
end

app/controllers/spree/admin/base_controller_decorator.rb
Spree::Admin::BaseController.class_eval do
  # def index
  #   if spree_current_user.has_spree_role? 'demo'
  #     redirect_to spree.admin_products_path
  #   else
  #     redirect_to admin_root_redirect_path
  #   end
  # end
end

app/controllers/spree/admin/products_controller_decorator.rb
Spree::Admin::ProductsController.class_eval do

  DATA_COLUMNS = [:name, {:author => [:name]}, :price, :price_type, :id, :created_at, :description, :description_short,
  :available_on, :discontinue_on, :promotionable, :shipping_category_id, :tax_category_id, :meta_description,
  :meta_keywords, :meta_title, :slug, :updated_at, {:images => [:first => [:url_with_host]]}]

  HEADER_COLUMNS = ['Name', 'Author', 'Price', 'Price_type', 'ID', 'Created', 'Description', 'Description_short',
  'Available_on', 'Discontinue_on', 'Promotionable', 'shipping_category_id', 'tax_category_id', 'meta_description',
   'meta_keywords', 'meta_title', 'slug', 'Updated_at', 'Image']

  def index
    respond_to do |format|
      format.html { render :index }
      format.xls do
        @products = Spree::Product.all
        send_data @products.to_xls(:columns => DATA_COLUMNS, :headers => HEADER_COLUMNS), :filename => 'products.xls'
      end
    end
  end

  def set_unavailable
    #@product = Spree::Product.find(:id)
    @product.available_on = nil
    @product.save!
    redirect_to admin_products_path
  end

  def set_available
    #@product = Spree::Product.find(:id)
    @product.available_on = Time.now
    @product.save!
    redirect_to admin_products_path
  end

  def product_includes
    [{ variants: [:images], master: [:images, :default_price] }, :author]
  end
end

app/controllers/spree/admin/taxons_controller_decorator.rb
Spree::Admin::TaxonsController.class_eval do
  # Spree::PermittedAttributes.taxon_attributes << [:show_on_home]
end

app/controllers/spree/admin/videos_controller_decorator.rb
Spree::Admin::VideosController.class_eval do

  private
  def load_data
    @product = Spree::Product.find_by(slug: params[:product_id] || (params[:video] && params[:video][:product_id]))
    @author  = Spree::Author.find_by(id: params[:author_id] || (params[:video] && params[:video][:author_id]))
  end

  def set_product
    @video.watchable = @product || @author
  end
end

app/controllers/spree/authors_controller.rb
module Spree
  class AuthorsController < Spree::StoreController
    before_action :load_author, only: :show
    helper 'spree/products'
    PER_PAGE = 20

    respond_to :html

    def index
      @authors = Spree::Author.all.page(params[:page]).per(PER_PAGE)
    end

    def show

    end

    private
    def load_author
      @author = Spree::Author.find_by_slug(params[:id])
    end
  end
end

app/controllers/spree/base_controller_decorator.rb
Spree::BaseController.class_eval do
  include Globals::ErrorPages

  def render_404
    raise ActiveRecord::RecordNotFound
  end
end

app/controllers/spree/errors_controller.rb
module Spree
  class ErrorsController < Spree::StoreController
    layout 'spree/layouts/spree_application'
    respond_to :js, :html

    def not_found
      render status: :not_found
    end

    def internal_server_error
      render status: :internal_server_error
    end

    def unprocessable_entity
      render status: :unprocessable_entity
    end
  end
end

app/controllers/spree/home_controller.rb
module Spree
  class HomeController < Spree::StoreController
    helper 'spree/products'
    respond_to :html

    def index
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products.includes(:possible_promotions)
      @taxonomies = Spree::Taxonomy.includes(root: :children)
      @videos = Spree::Video.stream_or_home_videos
      @sample_products = sample_products
      @taxon_roots = Spree::Taxon.all
    end

    private
    def sample_products
      Spree::Taxon.find_each.with_object({}) do |taxon, samples|
        if !samples[taxon.taxonomy] && taxon.products.any?
          samples[taxon.taxonomy] = taxon.products.sample
        end
      end
    end
  end
end

app/controllers/spree/landings_controller.rb
module Spree
  class LandingsController < ApplicationController
    include Spree::Core::ControllerHelpers::Store
    helper 'spree/products'
    def index
      @taxonomies = Spree::Taxonomy.includes(root: :children)
      @taxon_roots = Spree::Taxon.all
    end
  end
end

app/views/spree/products/_cart_form.html.haml
= form_for :order, url: populate_orders_path do |f|
  #inside-product-cart-form.row{"data-hook" => "inside_product_cart_form", :itemprop => "offers", :itemscope => "", :itemtype => "https://schema.org/Offer"}
    - if @product.variants_and_option_values(current_currency).any?
      #product-variants.col-md-6
        %h3.product-section-title= Spree.t(:variants)
        %ul.list-group
          - @product.variants_and_option_values(current_currency).each_with_index do |variant, index|
            %li
              = radio_button_tag "variant_id", variant.id, index == 0,    |
                'data-price' => variant.price_in(current_currency).money, |
                'data-in-stock' => variant.can_supply?                    |
              = label_tag "variant_id_#{ variant.id }" do
                %span.variant-description
                  = variant_options variant
                - if variant_price variant
                  %span.price.diff= variant_price variant
                - unless variant.can_supply?
                  %span.out-of-stock= Spree.t(:out_of_stock)
    - else
      = hidden_field_tag "variant_id", @product.master.id
    - if @product.price_in(current_currency) && !@product.price.nil?
      .col-md-12{"data-hook" => "product_price"}
        #product-price
          %h6.product-section-title= Spree.t(:price)
          %div
            .row
              .col-md-4
                %span.lead.price.selling{:itemprop => "price"}
                  - if @product.not_sale? || @product.request_price?
                    = product_price_variations
                  - if @product.real_price?
                    - if @product.discount > 0
                      .price-before-discount
                        = number_to_currency(@product.price_before_discount, :precision => 0)
                      .price_with_discount
                        = number_to_currency(@product.price, :precision => 0)
                    - else
                      .price_only
                        = number_to_currency(@product.price, :precision => 0)
                %span{:content => @product.currency, :itemprop => "priceCurrency"}

              .col-md-4
                - if @product.can_supply? && @product.real_price?
                  .add-to-cart.quantity_wanted_p
                    .apQty.js--cart-adjust
                      = hidden_field_tag :quantity, 1
                    %span.input-group-btn
                      = button_tag class: 'btn btn-success add_to_cart_detail', id: 'add-to-cart-button', type: :submit do
                        = Spree.t(:add_to_cart)
          - if @product.master.can_supply?
            %link{:href => "https://schema.org/InStock", :itemprop => "availability"}/
          - elsif @product.variants.empty?
            %span.out-of-stock= Spree.t(:out_of_stock)

    - else
      #product-price
        %br/
        %div
          %span.price.selling{:itemprop => "price"}
            = Spree.t('product_not_available_in_this_currency')

app/views/spree/products/_image.html.haml
- img_class ||= ''
- if defined?(image) && image
  = image_tag image.attachment.url(:product476), itemprop: 'image', class: img_class
- else
  = product476_image(@product, itemprop: 'image', class: img_class)

app/views/spree/products/_item_big.html.haml
- url = spree.product_url(product, taxon_id: @taxon.try(:id))
.product_block{data: {hook: 'products_list_item'}, :id => "product_#{product.id}", :itemscope => "", :itemtype => "https://schema.org/Product"}
  - cache(@taxon.present? ? [I18n.locale, current_currency, @taxon, product] : cache_key_for_product(product)) do
    .product-container.left-block
      .product-image-container.image
        %a.product_img_link{href: url, title: product.name}
          %img.replace-2x.img-responsive{alt: product.name, src: product_image_src(product, :product476)}/
          %span.product-additional{data: {idproduct: product.id}}
        -#%span.new-box
          %span.label-new.label New
        -#%span.sale-box
          %span.label-sale.label Sale
        -#.quickview
          %a.quick-view.btn.fancybox{rel: 'products-top-gallery', href: product_image_src(product, :product1024), title: truncate(product.name, length: 50), data: {handle: product.slug, img_src: product_image_src(product)}}
            %i.fa.fa-expand
      .product-meta
        .name
          %a.product-name.product-name-title{href: url, title: product.name}
            = truncate(product.name, length: 50)
        .product-desc.desc-short
          = product.description_short
      - if product_property(@product_properties, :year).present?
        %h5.brand{:itemprop => "brand"}
          %span Year:
          %a{:href => "/products/years?q=", :title => ""}= product_property(@product_properties, :year)
        -#.review
          %span#spr_badge_7135946433.spr-badge{"data-rating" => "5.0"}
            %span.spr-starrating.spr-badge-starrating
              %i.spr-icon.spr-icon-star{:style => ""}
              %i.spr-icon.spr-icon-star{:style => ""}
              %i.spr-icon.spr-icon-star{:style => ""}
              %i.spr-icon.spr-icon-star{:style => ""}
              %i.spr-icon.spr-icon-star{:style => ""}
            %span.spr-badge-caption
              1 review
        -#.content_price
          %span.old-price.product-price
            %span.money{"data-currency" => "USD", "data-currency-usd" => "$15.50"} $15.50
          %span.price.product-price
            %span.money{"data-currency" => "USD", "data-currency-usd" => "$12.00"} $12.00

app/views/spree/products/_item_small.html.haml
- url = spree.product_url(product, taxon_id: @taxon.try(:id))
.product-list-item{"data-hook" => "products_list_item", :id => "product_#{product.id}", :itemscope => "", :itemtype => "https://schema.org/Product"}
  - cache(@taxon.present? ? [I18n.locale, current_currency, @taxon, product] : cache_key_for_product(product)) do
    .product-container.text-left.product-block.block-index{"data-hook" => "products_list_item", :id => "product_#{product.id}", :itemscope => "", :itemtype => "https://schema.org/Product"}
      .product-image-container.image.img-index
        %a.product_img_link{href: url}
          = product476_image(product, itemprop: 'image', class: 'img-responsive')
          %span.product-additional{"data-idproduct" => product.id}
        -#%span.new-box
          %span.label-new.label New
        -#%span.sale-box
          %span.label-sale.label Sale
        -#.quickview
          %a.quick-view.product-quick-view.btn{href: 'javascript: return false;', title: '+ Quick View', data: {handle: product.slug, img_src: product_image_src(product)}}
            %i.fa.fa-expand
        -#.quickview
          %a.quick-view.btn.fancybox{rel: 'products-top-gallery', href: product_image_src(product), title: truncate(product.name, length: 50), data: {handle: product.slug, img_src: product_image_src(product)}}
            %i.fa.fa-expand
      .product-meta
        %h5.name
          %a.product-name.product-name-title{href: url, title: truncate(product.name, length: 50)}
            = truncate(product.name, length: 50)
        .product-desc
          != simple_format(truncate(product_description(product), length: 200))
        -#.review
          %span.spr-badge{"data-rating" => "5.0", id: "#spr_badge_#{product.id}"}
            %span.spr-starrating.spr-badge-starrating
              %i.spr-icon.spr-icon-star{:style => ""}
              %i.spr-icon.spr-icon-star{:style => ""}
              %i.spr-icon.spr-icon-star{:style => ""}
              %i.spr-icon.spr-icon-star{:style => ""}
              %i.spr-icon.spr-icon-star{:style => ""}
            %span.spr-badge-caption
              1 review
        -#.content_price
          %span.old-price.product-price
            %span.money{"data-currency" => "USD", "data-currency-usd" => display_price(product)}= display_price(product)
          %span.price.product-price.sale-price
            %span.money{"data-currency" => "USD", "data-currency-usd" => display_price(product)}= display_price(product)
        -#.functional-buttons.clearfix
          .wishlist
            %a.btn.btn-outline-inverse.btn-wishlist{:href => "#!account/login", :title => "Add to Wishlist"}
              %i.fa.fa-heart
              %span Add to Wishlist
          .cart
            .action
              %form.form-ajaxtocart{:action => "#!cart/add", :enctype => "multipart/form-data", :method => "post"}
                %input{name: :id, type: :hidden, value: product.id}/
                %button.button.ajax_addtocart{:title => "Add to Cart", :type => "submit", :value => "Submit"}
                  %span.fa.fa-shopping-cart
                  %span Add to Cart
          .view_detail
            %a.btn.lnk_view{href: url, title: "View product"}
              %i.fa.fa-retweet
              %span View product
-#.button_product_list.text-center
  %a.btn_home_page.btn.btn-center{href: products_path}
    View all items

app/views/spree/products/_promotions.html.haml
- promotions = @product.possible_promotions
- if promotions.any?
  #promotions
    %h3= Spree.t(:promotions)
    - promotions.each do |promotion|
      .well.well-sm
        %h4= promotion.name
        != simple_format(promotion.description)
        - if promotion.products.any?
          %ul
            - promotion.products.each do |product|
              %li= link_to product.name, product_path(product)

app/views/spree/products/_properties.html.haml
- unless @product_properties.empty?
  #categories_block.block.sidebarCategories
    %h4.title_block= Spree.t('properties')
    .block_content#product-properties{"data-hook" => ""}
      - @product_properties.each do |product_property|
        .row
          .col-sm-6
            %strong= product_property.property.presentation
          .col-sm-6
            = product_property.value

app/views/spree/products/_taxons.html.haml
- if @product.taxons.present?
  %h3.product-section-title= Spree.t(:look_for_similar_items)
  %ul#similar_items_by_taxon.list-group{"data-hook" => ""}
    - @product.taxons.each do |taxon|
      %li.list-group-item= link_to taxon.name, seo_url(taxon)

app/views/spree/products/_thumbnails.html.haml
- if (@product.images + @product.variant_images).uniq.size > 1
  %ul#product-thumbnails.thumbnails.list-inline{"data-hook" => ""}
    - @product.images.each do |i|
      %li{:class => "tmb-all tmb-#{i.viewable.id}"}
        = link_to(image_tag(i.attachment.url(:mini), class: "thumbnail product_img_link"), i.attachment.url(:product476), title: truncate(@product.name, length: 50), data: {handle: @product.slug, img_src: i.attachment.url(:original)})
    - if @product.has_variants?
      - @product.variant_images.each do |i|
        - next if @product.images.include?(i)
        %li{:class => "vtmb tmb-#{i.viewable.id}"}
          = link_to(image_tag(i.attachment.url(:mini), class: "thumbnail product_img_link"), i.attachment.url(:product476), title: truncate(@product.name, length: 50), data: {handle: @product.slug, img_src: i.attachment.url(:original)})

app/views/spree/products/_video_thumbnails.html.haml
- if videos.size > 1
  = content_tag(:div, id: 'video-thumbnails', class: 'spree-video-thumbnails') do
    - videos.map(&:youtube_data).each do |video|
      - product_video = videos.select{|v| v.youtube_ref == video.id}.try(:first)
      = link_to image_tag(spree_video_thumb_uri(video)), video_path(id: product_video, youtube_ref: video.id), title: video.title, class: 'spree-video-thumbnail', data: {'video-id' => video.id}, remote: true

app/views/spree/products/index.html.haml
- if "spree/products" == params[:controller] && @taxon || !@taxonomies.empty?
  - content_for :sidebar do
    %div{"data-hook" => "homepage_sidebar_navigation"}
      - if "spree/products" == params[:controller] && @taxon
        -#= render :partial => 'spree/shared/filters'
      - else
        = render :partial => 'spree/shared/taxonomies'
= render partial: 'spree/shared/products_sort_header'
- if params[:keywords]
  %div{"data-hook" => "search_results"}
    - if @products.empty?
      %h6.search-results-title= Spree.t(:no_products_found)
    - else
      = render :partial => 'spree/shared/products_big', :locals => { :products => @products, :taxon => @taxon }
- else
  %div{"data-hook" => "homepage_products"}
    - cache(cache_key_for_products) do
      = render :partial => 'spree/shared/products_big', :locals => { :products => @products, :taxon => @taxon }

app/views/spree/products/show.html.haml
- @body_id = 'product-details'
- cache cache_key_for_product do
  -#%aside
    #left_column.left_column.sidebar.col-sm-4.col-md-3.col-xs-12
      = render partial: 'spree/products/properties'
      = render partial: '/shared/products_best_sellers'

  #center_column.center_column
    - url = spree.product_url(@product, taxon_id: @taxon.try(:id))
    %div{itemscope: '', itemtype: 'http://schema.org/Product'}
      %meta{content: url, itemprop: 'url'}/
      %meta{content: product_image_src(@product), itemprop: 'image'}/
      .primary_block
        .row
          #product-images.product-left-column.col-xs-12.col-sm-12.col-md-5{"data-hook" => "product_images"}
            #main-image2.product-block{"data-hook" => ""}
              .product-image-container.image.img-wrap
                - product_image_orig = product_image_src(@product, :original)
                %a.fancybox.fancy-no-hide{title: @product.name, href: product_image_orig}
                  = render :partial => 'image', locals: {img_class: 'img-responsive'}
                -if @product.stock_items.first.try(:count_on_hand) == 0
                  %h1 SOLD
            #thumbnails.product-thumbs{"data-hook" => ""}
              = render :partial => 'thumbnails'
          .col-xs-12.col-sm-12.col-md-7
            .product-center-column
              %h4{:itemprop => "name"}= @product.name
              - @product_properties.each do |prop|
                %h5.brand{:itemprop => "brand"}
                  %span #{prop.property.name}:
                  = prop.value
              .product-description.rte{:itemprop => "description"}
                .product-desc.desc-short
                  != simple_format(product_description_short(@product))
              = render partial: 'products/info_block', locals: {product: @product}
            .product-right-column
              %div{:itemprop => "offers", :itemscope => "", :itemtype => "http://schema.org/Offer"}
                %meta{:content => @product.currency, :itemprop => "priceCurrency"}/
                %link{:href => "http://schema.org/InStock", :itemprop => "availability"}/
                -#= render partial: 'shared/deal_clock'
                - if @product.master.can_supply?
                  .availability
                    %p.available.instock Available
                = render partial: 'cart_form'
                -#= render partial: 'products/apollo_cart'
              -#.wishlist
                %a.btn.btn-outline-inverse.btn-wishlist{:href => "/account/login", :title => "Add to Wishlist"}
                  %i.fa.fa-heart
                  %span Add to Wishlist
              .line-product
              #product-detail-image
                .box_image_pd
                  = image_tag 'img_product_detail.png'
                  = link_to Spree.t(:inquire), pages_contact_us_path, class: 'btn btn-info'
                  = link_to Spree.t(:make_an_offer), pages_contact_us_path, class: 'btn btn-info'

        = render 'video', product: @product
      = render partial: 'shared/products_category', locals: { products: taxon_preview(@taxon), taxon: @taxon }  if @taxon && taxon_preview(@taxon).present?