config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  #if Rails.env.production?
    #match '/', to: 'spree/landings#index', via: 'get'
  #end
  mount Spree::Core::Engine, at: '/'
end
Spree::Core::Engine.add_routes do
  namespace :admin, path: Spree.admin_path do
    put 'products/:id/set_available', to: 'products#set_available', as: :make_product_available
    put 'products/:id/set_unavailable', to: 'products#set_unavailable', as: :set_unavailable_product
  end
end

Spree::Core::Engine.routes.append do
  namespace :admin, path: Spree.admin_path do
    resources :authors, path: 'artists' do
      resources :images, controller: :author_images do
        collection do
          post :update_positions
        end
      end
      resources :videos, path: 'library'
    end
  end

  resources :authors, only: [:index, :show], path: 'artists'
  resources :taxons do
    collection do
      get :products
    end
  end
  resources :videos, path: 'library' do
    collection do
      get :items
    end
  end
  get  'pages/contact_us'
  get  'pages/contact_artist'
  get  'pages/about_us', controller: 'pages', action: 'about_us'
  get  'pages/auctions', controller: 'pages', action: 'auctions'
  post 'pages/contact_us', controller: 'pages', action: 'contact_us_send'
  post 'pages/contact_artist', controller: 'pages', action: 'contact_artist_send'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable_entity', via: :all
end

app/models/spree/author_image.rb
# == Schema Information
#
# Table name: spree_assets
#
#  id                      :integer          not null, primary key
#  viewable_id             :integer
#  viewable_type           :string
#  attachment_width        :integer
#  attachment_height       :integer
#  attachment_file_size    :integer
#  position                :integer
#  attachment_content_type :string
#  attachment_file_name    :string
#  type                    :string(75)
#  attachment_updated_at   :datetime
#  alt                     :text
#  created_at              :datetime
#  updated_at              :datetime
#

module Spree
  class AuthorImage < Asset
    belongs_to :viewable, :polymorphic => true, :touch => true

    validate :no_attachment_errors

    has_attached_file :attachment,
                      styles: { mini: '48x48>', small: '100x100>', author: '240x240>', large: '600x600>' },
                      default_style: :author,
                      url: '/spree/authors/:id/:style/:basename.:extension',
                      path: ':rails_root/public/spree/authors/:id/:style/:basename.:extension',
                      convert_options: { all: '-strip -auto-orient -colorspace sRGB' }
    validates_attachment :attachment,
      :presence => true,
      :content_type => { :content_type => %w(image/jpeg image/jpg image/png image/gif) }

    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    before_save :find_dimensions, if: :attachment_updated_at_changed?

    def author_id
      viewable_id if viewable_type == 'Spree::Author'
    end

    #used by admin products autocomplete
    def mini_url
      attachment.url(:mini, false)
    end

    def original_url
      attachment.url(:original, false)
    end

    def url_with_host_author
      "#{ActionController::Base.asset_host}#{original_url}"
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end
  end
end

app/controllers/spree/admin/author_images_controller.rb
module Spree
  module Admin
    class AuthorImagesController < ResourceController
      before_action :load_data

      create.before :set_viewable
      update.before :set_viewable

      def show
        redirect_to [:admin, @author, :images]
      end

      private

      def location_after_destroy
        admin_author_images_url(@author)
      end

      def location_after_save
        admin_author_images_url(@author)
      end

      def location_create_save
        admin_author_images_url(@author)
      end

      def location_update_save
        admin_author_images_url(@author)
      end

      def load_data
        @author = Author.find(params[:author_id])
      end

      def set_viewable
        @author_image.viewable_type = 'Spree::Author'
        @author_image.viewable_id = params[:author_image][:viewable_id]
      end

      def author_index_includes
        [
            author_images: [viewable: { option_values: :option_type }]
        ]
      end

      def author_edit_includes
        [
            author_images: { option_values: :option_type, images: :viewable }
        ]
      end
    end
  end
end

app/views/spree/admin/author_images/_form.html.haml
.row{"data-hook" => "admin_image_form_fields"}
  .col-md-6
    .form-group{"data-hook" => "file"}
      = f.label :attachment, Spree.t(:filename)
      = f.file_field :attachment
    .form-group{"data-hook" => "author"}
      = f.label :viewable_id, Spree::Author.model_name.human
      = f.select :viewable_id, options_from_collection_for_select(Spree::Author.all, :id, :name, @author.id), {}, {:class => 'select2'}
  .col-md-6{"data-hook" => "alt_text"}
    .form-group
      = f.label :alt, Spree.t(:alt_text)
      = f.text_area :alt, :rows => 4, :class => 'form-control'

app/views/spree/admin/author_images/edit.html.haml
= render partial: 'spree/admin/shared/author_tabs', locals: { current: :images }
= render partial: 'spree/admin/shared/error_messages', locals: { target: @image }
= form_for [:admin, @author_image], url: admin_author_image_url(@author_image.viewable, @author_image), html: { multipart: true, method: :patch } do |f|
  .panel.panel-default{"data-hook" => "edit_image"}
    .panel-heading
      %h1.panel-title
        = @author_image.attachment_file_name
    .panel-body
      .form-group
        .col-md-3.text-center{"data-hook" => "thumbnail"}
          -#= f.label Spree.t(:thumbnail)
          = link_to image_tag(@author_image.attachment.url(:small)), @author_image.attachment.url(:large), title: @author_image.attachment_file_name, class: 'btn fancybox'
        .col-md-9
          = render partial: 'form', locals: { f: f }
        .form-actions{"data-hook" => "buttons"}
          = button Spree.t('actions.update'), 'save'
          %span.or= Spree.t(:or)
          = button_link_to Spree.t('actions.cancel'), spree.admin_author_images_url(@author), id: 'cancel_link', icon: 'delete'

app/views/spree/admin/author_images/index.html.haml
= render partial: 'spree/admin/shared/author_tabs', locals: { current: :images }
- content_for :page_actions do
  = button_link_to(Spree.t(:new_image), spree.new_admin_author_image_url(@author), { class: "btn-success", icon: 'add', id: 'new_image_link' }) if can? :create, Spree::Image

- return '' unless @author.try(:images)
%table.table.sortable{"data-hook" => "images_table", "data-sortable-link" => update_positions_admin_author_images_url(@author)}
  %thead
    %tr{"data-hook" => "images_header"}
      %th{:colspan => "2"}
        = Spree.t(:thumbnail)
      -#%th
        = Spree::Author.model_name.human
      %th
        = Spree.t(:alt_text)
      %th.actions
  %tbody
    - @author.images.each do |image|
      %tr{"data-hook" => "images_row", :id => spree_dom_id(image)}
        %td.move-handle.text-center
          - if can? :edit, image
            %span.icon.icon-move.handle
        %td.image
          = link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:large), class: 'btn fancybox'
        -#%td= options_text_for(image)
        %td= image.alt
        %td.actions.actions-2.text-right
          = link_to_with_icon('edit', Spree.t(:edit), spree.edit_admin_author_image_url(@author, image), class: 'btn btn-primary btn-sm', no_text: true, data: { action: 'edit' }) if can? :edit, image
          = link_to_delete(image, { url: spree.admin_author_image_url(@author, image), no_text: true, method: :delete }) if can? :destroy, image

app/views/spree/admin/author_images/new.html.haml
= render partial: 'spree/admin/shared/author_tabs', locals: { current: :images }
= render partial: 'spree/admin/shared/error_messages', locals: { target: @author }
- content_for :page_title do
  = Spree.t(:new_image)
= form_for [:admin, @author_image], html: { multipart: true } do |f|
  %fieldset{"data-hook" => "new_image"}
    = render partial: 'form', locals: { f: f }
    .form-actions{"data-hook" => "buttons"}
      = button Spree.t('actions.create'), 'save'
      %span.or= Spree.t(:or)
      = button_link_to Spree.t('actions.cancel'), spree.admin_author_images_url(@author), icon: 'delete', id: 'cancel_link'