config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  #if Rails.env.production?
    #match '/', to: 'spree/landings#index', via: 'get'
  #end
  mount Spree::Core::Engine, at: '/'
end
Spree::Core::Engine.add_routes do
  namespace :admin, path: Spree.admin_path do
    put 'products/:id/set_available', to: 'products#set_available', as: :make_product_available
    put 'products/:id/set_unavailable', to: 'products#set_unavailable', as: :set_unavailable_product
  end
end

Spree::Core::Engine.routes.append do
  namespace :admin, path: Spree.admin_path do
    resources :authors, path: 'artists' do
      resources :images, controller: :author_images do
        collection do
          post :update_positions
        end
      end
      resources :videos, path: 'library'
    end
  end

  resources :authors, only: [:index, :show], path: 'artists'
  resources :taxons do
    collection do
      get :products
    end
  end
  resources :videos, path: 'library' do
    collection do
      get :items
    end
  end
  get  'pages/contact_us'
  get  'pages/contact_artist'
  get  'pages/about_us', controller: 'pages', action: 'about_us'
  get  'pages/auctions', controller: 'pages', action: 'auctions'
  post 'pages/contact_us', controller: 'pages', action: 'contact_us_send'
  post 'pages/contact_artist', controller: 'pages', action: 'contact_artist_send'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/422', to: 'errors#unprocessable_entity', via: :all
end

app/models/concerns/spree/user_methods.rb
module Spree
  module UserMethods
    extend ActiveSupport::Concern

    include Spree::UserApiAuthentication
    include Spree::UserPaymentSource
    include Spree::UserReporting
    include Spree::RansackableAttributes

    included do
      has_many :role_users, class_name: 'Spree::RoleUser', foreign_key: :user_id, dependent: :destroy
      has_many :spree_roles, through: :role_users, class_name: 'Spree::Role', source: :role

      has_many :promotion_rule_users, class_name: 'Spree::PromotionRuleUser', foreign_key: :user_id, dependent: :destroy
      has_many :promotion_rules, through: :promotion_rule_users, class_name: 'Spree::PromotionRule'

      has_many :orders, foreign_key: :user_id, class_name: "Spree::Order"
      #has_many :store_credits, foreign_key: :user_id, class_name: 'Spree::StoreCredit'
      # remove store_credits from app

      belongs_to :ship_address, class_name: 'Spree::Address'
      belongs_to :bill_address, class_name: 'Spree::Address'

      self.whitelisted_ransackable_associations = %w[bill_address ship_address]
      self.whitelisted_ransackable_attributes = %w[id email]
    end

    # has_spree_role? simply needs to return true or false whether a user has a role or not.
    def has_spree_role?(role_in_question)
      spree_roles.any? { |role| role.name == role_in_question.to_s }
    end

    def last_incomplete_spree_order
      orders.incomplete.
        includes(line_items: [variant: [:images, :option_values, :product]]).
        order('created_at DESC').
        first
    end

    def analytics_id
      id
    end

    def total_available_store_credit
      #store_credits.reload.to_a.sum(&:amount_remaining)
    end
  end
end

app/models/spree/author.rb
# == Schema Information
#
# Table name: spree_authors
#
#  id                       :integer          not null, primary key
#  name                     :string
#  content                  :text
#  year_of_birth            :integer
#  year_of_death            :integer
#  category                 :integer
#  slug                     :string
#  foreign_link             :string
#  visible                  :boolean          default(TRUE)
#  meta_title               :string
#  meta_keywords            :string
#  meta_description         :string
#  layout                   :string
#  render_layout_as_partial :boolean          default(FALSE)
#  show_in_sidebar          :boolean          default(FALSE), not null
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#

class Spree::Author < ActiveRecord::Base

  CATEGORY_ARTIST   = 1
  CATEGORY_SCULPTOR = 2

  enum category: {
      artist:   CATEGORY_ARTIST,
      sculptor: CATEGORY_SCULPTOR
  }

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :category, presence: true
  validates :slug, :content, presence: true
  validates :slug, uniqueness: true
  validates :foreign_link, uniqueness: true, allow_blank: true

  has_many :products
  has_many :author_images, -> { order 'position ASC' }, as: :viewable
  delegate_belongs_to :author_images
  alias_method :images, :author_images

  has_many :videos, -> { order 'position ASC' }, :as => :watchable

  scope :visible, -> { where(visible: true) }
  scope :header_links, -> { where(show_in_header: true).visible }
  scope :sidebar_links, -> { where(show_in_sidebar: true).visible }

  before_validation :fill_slug

  def description
    content
  end

  def fill_slug
    self.slug = name.gsub(/\s+/, '_').underscore
  end

  protected
  def ransackable_attributes(auth_object = nil)
    super & %w(name)
  end
end

app/models/spree/author_image.rb
# == Schema Information
#
# Table name: spree_assets
#
#  id                      :integer          not null, primary key
#  viewable_id             :integer
#  viewable_type           :string
#  attachment_width        :integer
#  attachment_height       :integer
#  attachment_file_size    :integer
#  position                :integer
#  attachment_content_type :string
#  attachment_file_name    :string
#  type                    :string(75)
#  attachment_updated_at   :datetime
#  alt                     :text
#  created_at              :datetime
#  updated_at              :datetime
#

module Spree
  class AuthorImage < Asset
    belongs_to :viewable, :polymorphic => true, :touch => true

    validate :no_attachment_errors

    has_attached_file :attachment,
                      styles: { mini: '48x48>', small: '100x100>', author: '240x240>', large: '600x600>' },
                      default_style: :author,
                      url: '/spree/authors/:id/:style/:basename.:extension',
                      path: ':rails_root/public/spree/authors/:id/:style/:basename.:extension',
                      convert_options: { all: '-strip -auto-orient -colorspace sRGB' }
    validates_attachment :attachment,
      :presence => true,
      :content_type => { :content_type => %w(image/jpeg image/jpg image/png image/gif) }

    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    before_save :find_dimensions, if: :attachment_updated_at_changed?

    def author_id
      viewable_id if viewable_type == 'Spree::Author'
    end

    #used by admin products autocomplete
    def mini_url
      attachment.url(:mini, false)
    end

    def original_url
      attachment.url(:original, false)
    end

    def url_with_host_author
      "#{ActionController::Base.asset_host}#{original_url}"
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end
  end
end

app/models/spree/image_decorator.rb
Spree::Image.class_eval do

  def url_with_host
    "#{ActionController::Base.asset_host}#{mini_url}"
  end
end

app/models/spree/price_decorator.rb
Spree::Price.class_eval do

  attr_writer :price_before_discount
  def price_before_discount
    if discount
      amount + discount
    else
      amount
    end
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  belongs_to :author
  enum price_type: [ :real_price, :not_sale, :request_price ]
  delegate_belongs_to :master, :discount
  delegate_belongs_to :master, :price_before_discount
  self.whitelisted_ransackable_associations += %w(author)
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  scope :show_on_home, -> {where show_on_home: true}
  has_many :authors, through: :products
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  delegate_belongs_to :default_price, :discount
  delegate_belongs_to :default_price, :price_before_discount
end

app/models/spree/video_decorator.rb
Spree::Video.class_eval do
  attr_accessor :author_id
  belongs_to :author, -> {where spree_videos: {watchable_type: 'Spree::Author'}}, class_name: 'Author', foreign_key: :watchable_id
  scope :orderby, -> (opt) { order(opt.is_a?(Array) && opt[1] ? {opt[0] => opt[1]} : opt) }
  validates :youtube_ref, format: {with: /([\w-]+)(&.+)?$/, message: :incorrect_link, multiline: true}, if: Proc.new{|model| model.youtube_ref.present?}

  def embed_html(html5_config = {}, youtube_url_params = {})
#  if youtube_url_params.empty?
  #youtube_data.embed_html
  #else
    "<iframe width='560' height='315' src='//www.youtube.com/embed/#{youtube_ref}' frameborder='0' allowfullscreen></iframe>"
  #end
  end
end

app/controllers/spree/admin/author_images_controller.rb
module Spree
  module Admin
    class AuthorImagesController < ResourceController
      before_action :load_data

      create.before :set_viewable
      update.before :set_viewable

      def show
        redirect_to [:admin, @author, :images]
      end

      private

      def location_after_destroy
        admin_author_images_url(@author)
      end

      def location_after_save
        admin_author_images_url(@author)
      end

      def location_create_save
        admin_author_images_url(@author)
      end

      def location_update_save
        admin_author_images_url(@author)
      end

      def load_data
        @author = Author.find(params[:author_id])
      end

      def set_viewable
        @author_image.viewable_type = 'Spree::Author'
        @author_image.viewable_id = params[:author_image][:viewable_id]
      end

      def author_index_includes
        [
            author_images: [viewable: { option_values: :option_type }]
        ]
      end

      def author_edit_includes
        [
            author_images: { option_values: :option_type, images: :viewable }
        ]
      end
    end
  end
end

app/controllers/spree/admin/authors_controller.rb
module Spree
  module Admin
    class AuthorsController < ResourceController

      def index

      end
    end
  end
end

app/controllers/spree/admin/base_controller_decorator.rb
Spree::Admin::BaseController.class_eval do
  # def index
  #   if spree_current_user.has_spree_role? 'demo'
  #     redirect_to spree.admin_products_path
  #   else
  #     redirect_to admin_root_redirect_path
  #   end
  # end
end

app/controllers/spree/admin/products_controller_decorator.rb
Spree::Admin::ProductsController.class_eval do

  DATA_COLUMNS = [:name, {:author => [:name]}, :price, :price_type, :id, :created_at, :description, :description_short,
  :available_on, :discontinue_on, :promotionable, :shipping_category_id, :tax_category_id, :meta_description,
  :meta_keywords, :meta_title, :slug, :updated_at, {:images => [:first => [:url_with_host]]}]

  HEADER_COLUMNS = ['Name', 'Author', 'Price', 'Price_type', 'ID', 'Created', 'Description', 'Description_short',
  'Available_on', 'Discontinue_on', 'Promotionable', 'shipping_category_id', 'tax_category_id', 'meta_description',
   'meta_keywords', 'meta_title', 'slug', 'Updated_at', 'Image']

  def index
    respond_to do |format|
      format.html { render :index }
      format.xls do
        @products = Spree::Product.all
        send_data @products.to_xls(:columns => DATA_COLUMNS, :headers => HEADER_COLUMNS), :filename => 'products.xls'
      end
    end
  end

  def set_unavailable
    #@product = Spree::Product.find(:id)
    @product.available_on = nil
    @product.save!
    redirect_to admin_products_path
  end

  def set_available
    #@product = Spree::Product.find(:id)
    @product.available_on = Time.now
    @product.save!
    redirect_to admin_products_path
  end

  def product_includes
    [{ variants: [:images], master: [:images, :default_price] }, :author]
  end
end

app/controllers/spree/admin/taxons_controller_decorator.rb
Spree::Admin::TaxonsController.class_eval do
  # Spree::PermittedAttributes.taxon_attributes << [:show_on_home]
end

app/controllers/spree/admin/videos_controller_decorator.rb
Spree::Admin::VideosController.class_eval do

  private
  def load_data
    @product = Spree::Product.find_by(slug: params[:product_id] || (params[:video] && params[:video][:product_id]))
    @author  = Spree::Author.find_by(id: params[:author_id] || (params[:video] && params[:video][:author_id]))
  end

  def set_product
    @video.watchable = @product || @author
  end
end

app/controllers/spree/authors_controller.rb
module Spree
  class AuthorsController < Spree::StoreController
    before_action :load_author, only: :show
    helper 'spree/products'
    PER_PAGE = 20

    respond_to :html

    def index
      @authors = Spree::Author.all.page(params[:page]).per(PER_PAGE)
    end

    def show

    end

    private
    def load_author
      @author = Spree::Author.find_by_slug(params[:id])
    end
  end
end

app/controllers/spree/base_controller_decorator.rb
Spree::BaseController.class_eval do
  include Globals::ErrorPages

  def render_404
    raise ActiveRecord::RecordNotFound
  end
end

app/controllers/spree/errors_controller.rb
module Spree
  class ErrorsController < Spree::StoreController
    layout 'spree/layouts/spree_application'
    respond_to :js, :html

    def not_found
      render status: :not_found
    end

    def internal_server_error
      render status: :internal_server_error
    end

    def unprocessable_entity
      render status: :unprocessable_entity
    end
  end
end

app/controllers/spree/home_controller.rb
module Spree
  class HomeController < Spree::StoreController
    helper 'spree/products'
    respond_to :html

    def index
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products.includes(:possible_promotions)
      @taxonomies = Spree::Taxonomy.includes(root: :children)
      @videos = Spree::Video.stream_or_home_videos
      @sample_products = sample_products
      @taxon_roots = Spree::Taxon.all
    end

    private
    def sample_products
      Spree::Taxon.find_each.with_object({}) do |taxon, samples|
        if !samples[taxon.taxonomy] && taxon.products.any?
          samples[taxon.taxonomy] = taxon.products.sample
        end
      end
    end
  end
end

app/controllers/spree/landings_controller.rb
module Spree
  class LandingsController < ApplicationController
    include Spree::Core::ControllerHelpers::Store
    helper 'spree/products'
    def index
      @taxonomies = Spree::Taxonomy.includes(root: :children)
      @taxon_roots = Spree::Taxon.all
    end
  end
end

app/views/spree/pages/about_us.html.haml
%p Live Art TV is dedicated to exhibiting the finest contemporary artists of the world.
%p Live Art TV was created in 2016 by art and television entrepreneur, Albert Yaghoubzadeh of Milan, Italy. He has brought his unique vision for presenting art to the public using the new cutting-edge digital distribution. The company’s prime focus since its inception, has been to introduce European Masters as well as contemporary artists. With an ever expanding plethora of works from around the globe, this collection grows exponentially each day. The precursor to Live Art TV began in 2004, thirteen years ago in Milan, Italy as, EliteShopping.TV. Elite specialized in painting, sculpture, jewelry and works on paper by modern art contemporary masters. Elite Shopping.TV tightly focused solo exhibitions, broadcasting with illuminating contents. Elite became a forum for new and well known artists to promote their works for sale. EliteShopping.TV, Milan, Italy broadcasted for fourteen years, their shows of paintings, sculpture, antiques and jewelry through a home shopping format. Today, Live Art TV embraces its roots while also updating them for today’s digital world through the use of online streaming and TV channels including Roku, Amazon FireTV, AndroidTV, AppleTV, YouTube, Facebook and many others reaching worldwide audiences on a far grander scale. Live Art TV is staffed by knowledgeable telephone personel, certified art appraisers, and provides reliable customer service.

app/views/spree/pages/auctions.html.haml
Auctions

app/views/spree/pages/contact_artist.html.haml
%h4 CALL FOR ARTISTS / SUBMIT YOUR ARTWORK
%p Elite Shopping TV / Live Art TV encourages artists to submit their work for consideration and exhibition. If accepted, your works will appear for sale both on our website, www.livearttv.com, and will be featured on one of our live streaming broadcasts from our studio in Hawley, PA via Roku, Amazon TV, Android TV, Apple TV. Representation also extends to promotions on all major social media channels, press releases, and personalized PR efforts. This is a wonderful opportunity for artists to promote their work and take their career to an entirely new level.

%p All work submitted will be carefully reviewed by our knowledgeable in-house art appraiser, veteran art collector, and qualified staff members. To be considered, please email your portfolio images and a brief biography or send us a URL link to your website to: info@eliteshopping.tv.
#successMessage.alert.alert-success{style: 'display: none;'}
  %p
    %span.success-ico
    Message Sent
#failureMessage.alert.alert-error{style: 'display: none;'}
  %p
    %span.error-ico
    Sorry. Please try later.
#incompleteMessage.alert.alert-warning{style: 'display: none;'}
  %p Please, fill all fields before sending

.row
  .col-md-9.col-sm-12.col-xs-12
    -#%form#contact_form.contact-form{"accept-charset" => "UTF-8", :action => pages_contact_us_path, :method => "post"}
    = form_tag(pages_contact_artist_path, method: :post, id: 'contactForm1', action: 'contact_artist_send', class: 'contact-form', multipart: true) do
      %input{type: 'text', name: 'name', style: 'display: none;'}
      .contact-form-box
        %fieldset
          %h3.page-subheading
          .row
            .col-xs-12.col-sm-4.col-md-4
              .form-group
                %label.label--hidden{:for => "ContactFormName"} Name
                %input#ContactFormName.form-control.grey{:autocapitalize => "words", :name => "contact[name]", :placeholder => "Name", :type => "text", required: true}/
            .col-xs-12.col-sm-4.col-md-4
              .form-group
                %label.label--hidden{:for => "ContactFormEmail"} Email
                %input#ContactFormEmail.form-control.grey{:autocapitalize => "off", :autocorrect => "off", :name => "contact[email]", :placeholder => "Email", :type => "email", required: true}/
          .row
            .col-xs-12
              .form-group
                %label.label--hidden{:for => "ContactFormMessage"} Message
                %textarea#ContactFormMessage.form-control{:name => "contact[content]", :placeholder => "Message", :rows => "8"}
          .row
            .col-xs-12
              .form-group
                %label.label--hidden{:for => "ContactFormFile"}
                %input#ContactFormFile{:type => "file", :class=>"form-control btn-metis-7 btn-file", :name => "contact[files][]", multiple: true}
          .submit
            %input.btn.btn-outline{:type => "submit", :value => "Send"}/

app/views/spree/pages/contact_us.html.haml
%h1.text-uppercase Contact us

#successMessage.alert.alert-success{style: 'display: none;'}
  %p
    %span.success-ico
    Message Sent
#failureMessage.alert.alert-error{style: 'display: none;'}
  %p
    %span.error-ico
    Sorry. Please try later.
#incompleteMessage.alert.alert-warning{style: 'display: none;'}
  %p Please, fill all fields before sending

.row
  .col-md-9.col-sm-12.col-xs-12
    -#%form#contact_form.contact-form{"accept-charset" => "UTF-8", :action => pages_contact_us_path, :method => "post"}
    = form_tag(pages_contact_us_path, method: :post, remote: true, id: 'contactForm', class: 'contact-form') do
      %input{type: 'text', name: 'name', style: 'display: none;'}
      .contact-form-box
        %fieldset
          %h3.page-subheading send a message

          .row
            .col-xs-12.col-sm-4.col-md-4
              .form-group
                %label.label--hidden{:for => "ContactFormName"} Name
                %input#ContactFormName.form-control.grey{:autocapitalize => "words", :name => "contact[name]", :placeholder => "Name", :type => "text", :value => ""}/
            .col-xs-12.col-sm-4.col-md-4
              .form-group
                %label.label--hidden{:for => "ContactFormEmail"} Email
                %input#ContactFormEmail.form-control.grey{:autocapitalize => "off", :autocorrect => "off", :name => "contact[email]", :placeholder => "Email", :type => "email", :value => ""}/
            .col-xs-12.col-sm-4.col-md-4
              .form-group
                %label.label--hidden{:for => "ContactFormPhone"} Phone Number
                %input#ContactFormPhone.form-control.grey{:name => "contact[phone]", :pattern => "[0-9\\-]*", :placeholder => "Phone Number", :type => "tel", :value => ""}/

          .row
            .col-xs-12
              .form-group
                %label.label--hidden{:for => "ContactFormMessage"} Message
                %textarea#ContactFormMessage.form-control{:name => "contact[content]", :placeholder => "Message", :rows => "8"}

          .submit
            %input.btn.btn-outline{:type => "submit", :value => "Send"}/
  .col-md-3.col-sm-12.col-xs-12
    .box-contact-info.block
      .block_content
        .coninfo-des
        %ul.list-unstyled
          %li.address
            %span #{Spree::Config[:company_address]}
          %li.phone
            %span #{Spree::Config[:company_phone]}
          %li.email
            %a{:href => "mailto:#{Spree::Config[:company_email]}"} #{Spree::Config[:company_email]}